import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — Aria',
};

const CONTACT_EMAIL =
  process.env.NEXT_PUBLIC_SUPPORT_EMAIL ?? 'tanvirsifat51@gmail.com';

const EFFECTIVE_DATE = 'July 11, 2026';

function H2({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="mt-9 font-display text-lg font-bold tracking-tight text-text-base">
      {children}
    </h2>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <p className="mt-3 text-sm leading-relaxed text-muted">{children}</p>;
}

export default function TermsPage() {
  return (
    <article>
      <h1 className="font-display text-3xl font-bold tracking-tight text-text-base">
        Terms of Service<span className="text-primary">.</span>
      </h1>
      <p className="mt-2 font-mono text-xs tracking-wide text-muted">
        EFFECTIVE {EFFECTIVE_DATE.toUpperCase()}
      </p>

      <P>
        These Terms of Service (&quot;Terms&quot;) govern your use of Aria
        (&quot;the Service&quot;), a platform for creating, testing, and
        deploying AI-powered chat assistants. By creating an account or using
        the Service you agree to these Terms.
      </P>

      <H2>1. The Service</H2>
      <P>
        Aria lets you configure AI assistants with custom instructions and
        knowledge, chat with them, embed them on your websites, and access them
        programmatically via API keys. Assistant responses are generated by
        third-party large language models; we route your assistant
        configuration and conversation content to those providers to produce
        replies.
      </P>

      <H2>2. Accounts</H2>
      <P>
        You must provide accurate information when registering and keep your
        credentials secure. You are responsible for all activity under your
        account, including activity performed with your API keys. Notify us
        immediately if you believe your account or a key has been compromised.
      </P>

      <H2>3. Acceptable use</H2>
      <P>
        You may not use the Service to: violate any law; generate or distribute
        malware; harass, defraud, or deceive others; produce content that
        infringes third-party rights; probe or disrupt the Service&apos;s
        infrastructure; resell the Service without authorization; or attempt to
        bypass usage limits, rate limits, or plan restrictions. Assistants you
        deploy to end users are your responsibility — you must ensure their use
        complies with applicable law and with the acceptable-use policies of
        the underlying model providers.
      </P>

      <H2>4. AI-generated content</H2>
      <P>
        Assistant output is generated automatically and may be inaccurate,
        incomplete, or inappropriate despite your instructions. The Service is
        not a substitute for professional advice. You are responsible for
        reviewing output before relying on it or presenting it to your own
        users, and for disclosing to your users that they are interacting with
        an AI system where required by law.
      </P>

      <H2>5. Plans, billing, and limits</H2>
      <P>
        Paid plans are billed monthly in advance through Stripe and renew
        automatically until canceled. You can cancel at any time from the
        billing page; access continues until the end of the paid period.
        Message and assistant limits per plan are enforced automatically.
        Except where required by law, fees are non-refundable. We may change
        pricing with at least 14 days&apos; notice, effective at your next
        renewal.
      </P>

      <H2>6. Your content</H2>
      <P>
        You retain all rights to the instructions, knowledge bases, and
        conversation content you submit. You grant us a limited license to
        store and process that content solely to operate the Service —
        including transmitting it to the AI model provider that generates
        responses. We do not sell your content.
      </P>

      <H2>7. Termination</H2>
      <P>
        You may delete your account at any time. We may suspend or terminate
        accounts that violate these Terms, create risk for the Service or other
        users, or remain unpaid after notice. Upon termination we may delete
        your data after a reasonable retention window.
      </P>

      <H2>8. Disclaimers and liability</H2>
      <P>
        The Service is provided &quot;as is&quot; without warranties of any
        kind, express or implied, including fitness for a particular purpose
        and non-infringement. To the maximum extent permitted by law, our total
        liability for any claim arising out of the Service is limited to the
        amount you paid us in the 12 months preceding the claim, and we are not
        liable for indirect, incidental, or consequential damages.
      </P>

      <H2>9. Changes to these Terms</H2>
      <P>
        We may update these Terms from time to time. Material changes will be
        announced by email or in-app notice at least 14 days before they take
        effect. Continued use of the Service after that date constitutes
        acceptance.
      </P>

      <H2>10. Contact</H2>
      <P>
        Questions about these Terms: <strong>{CONTACT_EMAIL}</strong>
      </P>
    </article>
  );
}
